@host = http://localhost:3010
@userId = author-uuid-002
@postId = post-uuid-T1
@commentId = comment-uuid-1
@token = eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjY1ZTE0MDg3OGQ1ODU4M2YzYjQ3ZDk4MCIsImVtYWlsIjoiYWxleDIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzA5MzIwOTgxLCJleHAiOjE3MDk0OTM3ODF9.MinzPY09243qznrA0vUDVXzxYFpUxfGhYs_y43ZI8VsMTR3TmlturjjyXSUV696IdTpQlm_e7QTbU0boxboo0w

# Create a new Comment for Post
POST {{host}}/api/comment/post/{{postId}}/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "text": "Google is good for search."
}

###

# Get Comment by ID
GET {{host}}/api/comment/{{commentId}} HTTP/1.1

###

# Get All Comments by Post ID
GET {{host}}/api/comment/post/{{postId}} HTTP/1.1

###

# Update Comment by ID
PATCH {{host}}/api/comment/{{commentId}}/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "text": "Google is good for search!!!"
}

###

# Delete Comment by ID
DELETE {{host}}/api/comment/{{commentId}}/{{userId}} HTTP/1.1

###
