@host = http://localhost:3040
@userId = 661c2da73755ed24c779f041
@postId = 9721f2e7-162f-47d1-a423-7a0324e3ecc3
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMxNDFjZGU5ZmIwYjBmODAyYzllNDgiLCJlbWFpbCI6InVzZXIxMTJAbm90Zm91bmQubG9jYWwiLCJ1c2VyVHlwZSI6InVzZXIiLCJmaXJzdE5hbWUiOiJLZWtzIiwibGFzdE5hbWUiOiJBQUEyIiwiaWF0IjoxNzE1MzAzNjA0LCJleHAiOjE3MTc4OTU2MDR9.wt0Q-DxgBgOq9qLcZ1AAlxWRIsTdhTL8xn_ODROJb5FrMHqIimmav6mqC7vHZX3cmFhaAY29bO0klGFVqdXwLQ

# Get Link-post by ID
GET {{host}}/api/post/general/{{postId}} HTTP/1.1

###

# Delete Post by ID
DELETE {{host}}/api/post/general/{{postId}} HTTP/1.1
Authorization: Bearer {{token}}

###

# Like Post by ID
POST {{host}}/api/post/general/{{postId}}/like HTTP/1.1
Authorization: Bearer {{token}}

###

# Unlike Post by ID
DELETE {{host}}/api/post/general/{{postId}}/like HTTP/1.1
Authorization: Bearer {{token}}

###
