@host = http://localhost:3000
@userId = 6629510ff7987067e6076a82
@subscribeUserId = 6629512cf7987067e6076a85
@token = eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjY1ZTE0MDg3OGQ1ODU4M2YzYjQ3ZDk4MCIsImVtYWlsIjoiYWxleDIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzA5MzIwOTgxLCJleHAiOjE3MDk0OTM3ODF9.MinzPY09243qznrA0vUDVXzxYFpUxfGhYs_y43ZI8VsMTR3TmlturjjyXSUV696IdTpQlm_e7QTbU0boxboo0w

# Create a new user
POST {{host}}/api/user HTTP/1.1
Content-Type: application/json

{
  "email": "user112@notfound.local",
  "firstName": "Keks",
  "lastName": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET {{host}}/api/user/{{userId}} HTTP/1.1

###

# Update user by ID
PATCH {{host}}/api/user/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "lastName": "AAA2"
}

###

# Subscribe User
POST {{host}}/api/user/subscription/{{subscribeUserId}}/{{userId}} HTTP/1.1

###

# Unsubscribe User
DELETE {{host}}/api/user/subscription/{{subscribeUserId}}/{{userId}} HTTP/1.1

###
