@host = http://localhost:3000
@userId = 6629510ff7987067e6076a82
@subscribeUserId = 6629512cf7987067e6076a85
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMxNDFjZGU5ZmIwYjBmODAyYzllNDgiLCJlbWFpbCI6InVzZXIxMTJAbm90Zm91bmQubG9jYWwiLCJ1c2VyVHlwZSI6InVzZXIiLCJmaXJzdE5hbWUiOiJLZWtzIiwibGFzdE5hbWUiOiJTbWl0aCIsImlhdCI6MTcxNDc2MDYzNiwiZXhwIjoxNzE0NzYwOTM2fQ.zNWLnfpPaC5R7kGpGscY_bs2DZH0JgMpUdaqbIKAKV-LqAhh3HToYMWoIbsuyJ7h5z4vz4WJGx3qHXtW4VF1RA

# Create a new user
POST {{host}}/api/user HTTP/1.1
Content-Type: application/json

{
  "email": "user112@notfound.local",
  "firstName": "Keks",
  "lastName": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET {{host}}/api/user/{{userId}} HTTP/1.1
Authorization: Bearer {{token}}

###

# Update user by ID
PATCH {{host}}/api/user/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "lastName": "AAA2"
}

###

# Subscribe User
POST {{host}}/api/user/subscription/{{subscribeUserId}}/{{userId}} HTTP/1.1

###

# Unsubscribe User
DELETE {{host}}/api/user/subscription/{{subscribeUserId}}/{{userId}} HTTP/1.1

###
