@host = http://localhost:3010
@userId = 661c2da73755ed24c779f0412
@postId = 6b0e0ca6-cd60-405d-b935-edd179ca4767
@token = eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjY1ZTE0MDg3OGQ1ODU4M2YzYjQ3ZDk4MCIsImVtYWlsIjoiYWxleDIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzA5MzIwOTgxLCJleHAiOjE3MDk0OTM3ODF9.MinzPY09243qznrA0vUDVXzxYFpUxfGhYs_y43ZI8VsMTR3TmlturjjyXSUV696IdTpQlm_e7QTbU0boxboo0w

###

# Get Link-post by ID
GET {{host}}/api/post/{{postId}} HTTP/1.1

###

# Delete Post by ID
DELETE {{host}}/api/post/{{postId}}/{{userId}} HTTP/1.1

###

# Like Post by ID
POST {{host}}/api/post/{{postId}}/like/{{userId}} HTTP/1.1

###

# Unlike Post by ID
DELETE {{host}}/api/post/{{postId}}/like/{{userId}} HTTP/1.1

###
