@host = http://localhost:3030
@userId = 661c2da73755ed24c779f041
@postId = 51377bc9-afa8-4e05-ba48-9fa8dea9a122
@token = eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjY1ZTE0MDg3OGQ1ODU4M2YzYjQ3ZDk4MCIsImVtYWlsIjoiYWxleDIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzA5MzIwOTgxLCJleHAiOjE3MDk0OTM3ODF9.MinzPY09243qznrA0vUDVXzxYFpUxfGhYs_y43ZI8VsMTR3TmlturjjyXSUV696IdTpQlm_e7QTbU0boxboo0w
@fileId = 662d6205cac7998bce449c75

# Start Email Servise for new posts
POST {{host}}/api/notifications/new-post/{{userId}} HTTP/1.1

###
